{
  buildLinux,
  lib,
  pkgs,
  kernelUrl,
  kernelRef,
  kernelRev ? null,
  ...
} @ args:
buildLinux (args
  // rec {
    src = builtins.fetchGit ({
        url = kernelUrl;
        shallow = true;
        ref = kernelRef;
      }
      // lib.optionalAttrs (kernelRev != null) {
        rev = kernelRev;
      });

    version = builtins.readFile (
      pkgs.runCommand "kernel-version" {}
      ''
        cd ${src} && \
        echo -n $(make kernelversion) > $out
      ''
    );

    # this fixes an issue with kernelFeatures being a set instead of a list
    kernelPatches = [];

    # don't use the default config generated by Nix
    enableCommonConfig = false;

    # use the smallest base possible and add KVM guest additions
    defconfig = "tinyconfig kvm_guest.config";

    # avoid enabling a lot of modules due to enabling CONFIG_MODULES below
    autoModules = false;

    # prefer builtins instead of modules
    kernelPreferBuiltin = true;

    structuredExtraConfig = with lib.kernel; {
      # not actually used but assumed by called Nix functions
      MODULES = option yes;
      # enable some internal features that were disabled by tinyconfig
      EXPERT = option no;
      # support booting from initrd and running scripts
      BLK_DEV_INITRD = option yes;
      BINFMT_SCRIPT = option yes;
      # this is used by the init script and udev/systemd
      TMPFS = option yes;
      DEVTMPFS = option yes;
      INOTIFY_USER = option yes;
      AUTOFS_FS = option yes;
      CGROUPS = option yes;
      # required for QEMU (or something else that checks for them when building the initrd)
      VIRTIO_BALLOON = option yes;
      VIRTIO_MMIO = option yes;
      # nixos qemu-guest profile loads virtio_gpu in the initrd
      DRM = option yes;
      DRM_VIRTIO_GPU = option yes;
      HW_RANDOM = option yes;
      HW_RANDOM_VIRTIO = option yes;
      SCSI = option yes;
      SCSI_VIRTIO = option yes;
      BLK_DEV_SR = option yes;
      BLK_DEV_SD = option yes;
      CHR_DEV_SG = option yes;
      CHR_DEV_SCH = option yes;
      SATA_HOST = option yes;
      SATA_AHCI = option yes;
      EXT4_FS = option yes;
      OVERLAY_FS = option yes;
      RAID_ATTRS = option yes;
      ATA = option yes;
      MD = option yes;
      # networking
      IP_ADVANCED_ROUTER = option yes;
      IP_MULTIPLE_TABLES = option yes;
      IPV6_MULTIPLE_TABLES = option yes;
      PACKET = option yes;
      # IPsec dependencies
      XFRM_USER = option yes;
      XFRM_INTERFACE = option yes;
      XFRM_STATISTICS = option yes;
      INET_ESP = option yes;
      INET6_ESP = option yes;
      CRYPTO_AES = option yes;
      CRYPTO_GCM = option yes;
      TUN = option yes;
      # Incus dependencies
      FUSE_FS = option yes;
      VIRTIO_FS = option yes;
      BRIDGE = option yes;
      NETFILTER = option yes;
      MACVLAN = option yes;
      MACVTAP = option yes;
      TAP = option yes;
      BTRFS_FS = option yes;
      BTRFS_FS_POSIX_ACL = option yes;
      EXT4_FS_POSIX_ACL = option yes;
      EXT4_FS_SECURITY = option yes;
      SYSVIPC = option yes;
      NAMESPACES = option yes;
      UTS_NS = option yes;
      USER_NS = option yes;
      TIME_NS = option yes;
      IPC_NS = option yes;
      PID_NS = option yes;
      NET_NS = option yes;
      CGROUP_PIDS = option yes;
      CGROUP_FREEZER = option yes;
      CGROUP_DEVICE = option yes;
      CGROUP_SCHED = option yes;
      BLK_CGROUP = option yes;
      NFT_MASQ = option yes;
      NF_CT_NETLINK = option yes;
      NF_TABLES = option yes;
      NF_TABLES_INET = option yes;
      NETFILTER_NETLINK = option yes;
      NF_CONNTRACK = option yes;
      NF_NAT = option yes;
      NFT_NAT = option yes;
      VETH = option yes;
      # for Debug make it optional?
      IKCONFIG = option yes;
      IKCONFIG_PROC = option yes;
      # for ISO imag
      BLK_DEV_LOOP = option yes;
      VFAT_FS = option yes;
      NLS_CODEPAGE_437 = option yes;
      NLS_ISO8859_1 = option yes;
      UDF_FS = option yes;
      CIFS = option yes;
      JFS_FS = option yes;
      NTFS_FS = option yes;
      REISERFS_FS = option yes;
      MISC_FILESYSTEMS = option yes;
      BLOCK = option yes;
      USB = option yes;
      USB_SUPPORT = option yes;
      USB_STORAGE = option yes;
      SQUASHFS = option yes; # does not work as builtin magiclly selected as module
      ISO9660_FS = option yes;
      JOLIET = option yes;
      ZISOFS = option yes;
      UFS_FS = option yes;
      CRAMFS = option yes;
      DAX = option yes;
      MATCH_COMMENT = option yes;
      NETFILTER_XT_TARGET_CHECKSUM = option yes;
      VHOST = option yes;
      CRYPTO_SHA1_SSSE3 = option yes;
      CRYPTO_SHA256_SSSE3 = option yes;
      CRYPTO_SHA512_SSSE3 = option yes;
      CRYPTO_SHA512 = option yes;
      CDROM = option yes;
      USB_UAS = option yes;
      CRYPTO_CRC32C = option yes;
      CRYPTO_CRC32 = option yes;
      PROC_FS = option yes;
      SYSFS = option yes;
      FS_PID = option yes;
      BLK_DEV_SR_VENDOR = option yes;
      FUTEX = option yes;
      DEVMAPPER = option yes;
      LOCKD = option yes;
      FILE_LOCKING = option yes;
      OVERLAY_FS_REDIRECT_DIR = option yes;
      CONFIGFS_FS = option yes;
      SQUASHFS_XATTR = option yes;
      SQUASHFS_LZ4 = option yes;
      AIO = option yes;
      MODULE_COMPRESS_XZ = option yes;
      SQUASHFS_XZ = option yes;
      # 7os
      BLK_DEV_DM = option module;
      DM_MULTIPATH = option module;
      DM_VERITY = option module;
      DM_VERITY_VERIFY_ROOTHASH_SIG = option yes;
      EROFS_FS = option yes;
      TCG_TPM = option yes;
      TCG_TIS = option yes;
      TCG_CRB = option yes;
      ACPI = option yes;
      IMA = option yes;
      EFI = option yes;
      EFI_STUB = option yes;
      EFIVAR_FS = option yes;
      EFI_MIXED = option yes;
      VHOST_MENU = option yes;
      IP_NF_IPTABLES = option yes;
      NETFILTER_XT_MATCH_COMMENT = option yes;
      IP_NF_TARGET_MASQUERADE = option yes;
      NF_NAT_MASQUERADE = option yes;
      IP6_NF_IPTABLES = option yes;
      TMPFS_XATTR = option yes;
      TMPFS_INODE64 = option yes;
      TMPFS_POSIX_ACL = option yes;
      USB_XHCI_HCD = option yes;
      CRYPTO_DEV_VIRTIO = option yes;
    };
  }
  // (args.argsOverride or {}))
